services:
  account:
    image: abhisamd02/account:0.0.1-SNAPSHOT
    container_name: account_ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 768M
    networks:
        - lazybank
  loan:
    image: abhisamd02/loan:0.0.1-SNAPSHOT
    container_name: loan_ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 768M
    networks:
      - lazybank
  cards:
    image: abhisamd02/cards:0.0.1-SNAPSHOT
    container_name: cards_ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 768M
    networks:
      - lazybank

networks:
  lazybank:
    driver: bridge