spring:
  application:
    name: account-service

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "qa"

build:
  version: "3.0"
server:
  port: 8080

account:
  message: Welcome to Lazy Bank Dev - Account"
  contactDetails:
    name: "Abhishek Deepak - Developer"
    email: "abhishek@lazybank.co.in"
    phone: "+91-9876543210"
  onCallSupport:
    - (555) 123-4567
    - (555) 987-6543
